### ISSUE TITLE
Move ECR credential generation to static initialization code

### ISSUE THREAD

**Issue by jodymlin** [arvindsoni80/sigverify#1]
https://github.com/arvindsoni80/sigverify/blob/2047717067a5f97f1479cb2618e75b8dca68d13b/sigverify/sigverify.py#L78

https://github.com/arvindsoni80/sigverify/blob/2047717067a5f97f1479cb2618e75b8dca68d13b/sigverify/sigverify.py#L28-L29

To improve the runtime of the lambda by a few seconds (and also avoid throttling issues), we can pull these lines out into the static lambda initialization code (outside of the functions). That way the credentials will be generated once when the lambda container is first provisioned (this lambda invocation will be the longest) and then will be reused if/when the lambda container is also reused (which will cut down on the runtime of those invocations).

**Comment by arvindsoni80** [comment]
As discussed this will make us put the creds either in global or env. Let us keep it this way for now see what we hear.
