### ISSUE TITLE
Remove `Sid` from IAM policies

### ISSUE THREAD

**Issue by jodymlin** [arvindsoni80/sigverify#2]
https://github.com/arvindsoni80/sigverify/blob/2047717067a5f97f1479cb2618e75b8dca68d13b/.example_lambda_iam_policy.json#L6-L23

nit: We can probably remove the `Sid` lines since they are not required by ECR or Signer and we are not making these with the visual editor. Or, we can use the `Sid` line to give a brief descriptive title to each of these policies

**Comment by arvindsoni80** [comment]
removed sid
