### ISSUE TITLE
Increase Lambda timeout

### ISSUE THREAD

**Issue by jodymlin** [arvindsoni80/sigverify#3]
https://github.com/arvindsoni80/sigverify/blob/2047717067a5f97f1479cb2618e75b8dca68d13b/.example_template.yaml#L11

Not sure how fast your lambda code runs with all the client initializations, but in my original sample the first Lambda initialization always takes longer than 3 seconds (I think it hovers around 4-5 seconds). Subsequent invocations are shorter due to the usage of static code initialization. 

Out of fear of timeouts on the first invocation, I might increase this value.

**Comment by arvindsoni80** [comment]
changed to 5s
