### ISSUE TITLE
Add table of contents to README for readability

### ISSUE THREAD

**Issue by jodymlin** [arvindsoni80/sigverify#4]
https://github.com/arvindsoni80/sigverify/blob/2047717067a5f97f1479cb2618e75b8dca68d13b/README.md?plain=1#L6

A small suggestion would be to add a table of contents (bulletpoints works great) to make it more readable and understand the overview of the repo. The README is rather long so it makes it nice to see all the headers as a quick way to navigate and get a high level summary of what to expect. 

It might look something similar to this
```md
- [Getting Started](#getting-started)
    - [Preqrequisites](#prerequisites)
    - [Signing container images](#signing-container-images)
 ...etc.
```

**Comment by arvindsoni80** [comment]
static ToC is hard to maintain. I added site page using mkdocs - https://arvindsoni80.github.io/sigverify/
