### ISSUE TITLE
RPM lambda layer script does not match README platform

### ISSUE THREAD

**Issue by jodymlin** [arvindsoni80/sigverify#5]
https://github.com/arvindsoni80/sigverify/blob/2047717067a5f97f1479cb2618e75b8dca68d13b/create-lambda-layer.sh#L5-L7

The steps listed in this script are for Linux machines that support RPM. The README goes through an example with on Mac though which uses a different installer. I'd say we keep these the same for consistency and add commentary to the script that the installer instructions vary depending on the OS used. (Those instructions can also be found in [our docs](https://docs.aws.amazon.com/signer/latest/developerguide/image-signing-prerequisites.html))

**Comment by arvindsoni80** [comment]
Lambda still runs in Linux. I will add that to clarify.
